### ISSUE TITLE
TypeError: "'module' object is not callable"

### ISSUE THREAD

**Issue by MaximAbdulatif** [samirian/all_twitter_scraper#1]
Hi there @samirian, I am getting this error, any idea? 
شكرا سلفاً

![Screenshot 2020-07-18 at 17 44 08](https://user-images.githubusercontent.com/20270945/87856294-7c4f6000-c91e-11ea-810d-7b786a526e90.jpg)

**Comment by samirian** [comment]
@MaximAbdulatif your issue is related to a wrong import you have to replace the first line in your code with : from all_twitter_scraper.modules.Twitter_Scraper import Twitter_Scraper

**Comment by MaximAbdulatif** [comment]
Great! Thanks man, If you ever come to Utrecht I'll buy you a coffee :)
